### ISSUE TITLE
Include JavaScript inline?

### ISSUE THREAD

**Issue by alphapapa** [lorniu/ox-spectacle#1]
Hi,

This is really neat, and your demo is awesome.  However, I noticed that it requires loading JS from unpkg.com.  It would be very helpful if `ox-spectacle` could include the JS either inline or as files in an `export` subdirectory (like how Org export themes work), that way presentations would be self-contained and would work even without Internet access.

**Comment by lorniu** [comment]
I'll add later if anyone is interested in this.

**Comment by lorniu** [comment]
I have rewritten it, please try again.🤣
