### ISSUE TITLE
C-c C-e s f导出pdf后，chrome打开html文件后不显示内容

### ISSUE THREAD

**Issue by Elonisme** [lorniu/ox-spectacle#4]
控制台报错：DevTools 无法加载来源映射：无法加载 https://unpkg.com/spectacle@%5E4/dist/spectacle.js.map 的内容：HTTP 错误：状态代码 404，

**Comment by lorniu** [comment]
你是不是安装过旧的版本？重装下试试。

`M-x package-delete ox-spectacle`

然后:

`M-x package-install ox-spectacle`

**Comment by Elonisme** [comment]
> 你是不是安装过旧的版本？重装下试试。
> 
> `M-x package-delete ox-spectacle`
> 
> 然后:
> 
> `M-x package-install ox-spectacle`

腾讯云的镜像有点旧，2018年的，已经手动安装了，在ini.el 内添加了(add-to-list 'load-path "~/.emacs.d/elpa/ox-spectacle")
