### ISSUE TITLE
file name with underscore

### ISSUE THREAD

**Issue by randomwangran** [lorniu/ox-spectacle#6]
If I have in a file with org-mode on and export using ox-spectacle:

`<img src="./2023-03-02_screen.png"/>`

It converts into HTML file:

`2023-03-02</sub>screen.png`

But what is expected: 

`2023-03-02_screen.png`

**Comment by lorniu** [comment]
I have not been able to reproduce the problem.
Can you provide me with your org text fragment so I can test with?

![image](https://user-images.githubusercontent.com/265192/222884674-25490af6-abb0-4aad-98b1-0c1eb9de0cf5.png)

**Comment by randomwangran** [comment]
![image](https://user-images.githubusercontent.com/8197831/222925120-abf0b6ed-910d-465e-954a-c07e6f8b322d.png)

**Comment by lorniu** [comment]
Updated, please test.

Note: the syntax of sub/superscript must writen like `xxx^{2}` to distinguish `_^` in links.

**Comment by randomwangran** [comment]
sorry, haven't do any presentation recently. will update when necessary.
